census-instrumentation/opencensus-cpp

tools/ci.sh
=> ci.sh: exit successfully if there are no affected buildable files.

opencensus/BUILD, opencensus/copts.bzl
GCC_FLAGS don't work (we get an error about /Wextra)
https://github.com/census-instrumentation/opencensus-cpp/issues/6
=> Use MSVC_FLAGS with MSVC.

WORKSPACE, opencensus/exporters/stats/prometheus/BUILD, opencensus/exporters/stats/prometheus/internal/prometheus_exporter.cc, opencensus/exporters/stats/prometheus/internal/prometheus_test_server.cc, opencensus/exporters/stats/prometheus/internal/prometheus_utils.cc, opencensus/exporters/stats/prometheus/internal/prometheus_utils.h, opencensus/exporters/stats/prometheus/internal/prometheus_utils_test.cc, opencensus/exporters/stats/prometheus/prometheus_exporter.h
=> Add a Prometheus exporter

examples/helloworld/helloworld.cc
This reflects the default gRPC views which use bytes as units.
=> Change MBy to By units.

examples/helloworld/helloworld.cc
Fixes the opencensus-cpp part of #112.
=> Fix documentation of bucket boundaries in the helloworld example.

opencensus/stats/BUILD, opencensus/stats/distribution.h, opencensus/stats/internal/measure_data.cc, opencensus/stats/internal/measure_data.h, opencensus/stats/internal/measure_data_test.cc
Another part of the DeltaProducer--this tracks all aggregations (including potentially multiple histograms) on a measure.
=> Add the MeasureData class.

examples/grpc/BUILD, google/api/BUILD, google/devtools/cloudtrace/v2/BUILD, google/monitoring/v3/BUILD, google/rpc/BUILD, opencensus/plugins/grpc/internal/testing/BUILD
=> Remove generate_mocks arguments--these have been renamed and made optional.

opencensus/stats/internal/aggregation_window.cc, opencensus/stats/internal/aggregation_window.h, opencensus/stats/internal/debug_string_test.cc, opencensus/stats/internal/stats_manager.cc, opencensus/stats/internal/stats_manager.h, opencensus/stats/internal/stats_manager_test.cc, opencensus/stats/internal/view.cc, opencensus/stats/internal/view_data_impl.cc, opencensus/stats/internal/view_data_impl.h
For gRPC LB support. This does not depend on the DeltaProducer PRs.
=> Add delta aggregation as an internal interface.

.travis.yml, tools/appveyor/install.bat
I do not know of any issues with 0.8, but I think we may as well keep up.
=> Update Travis and Appveyor's Bazel version.

opencensus/common/internal/random_benchmark.cc
Also update benchmark loop syntax to its present recommendation.
=> Add a benchmark for RandomBuffer

opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
Counterpart to https://github.com/census-instrumentation/opencensus-java/pull/1087.
=> Change Stackdriver units to "1" for count views.

opencensus/exporters/stats/prometheus/internal/prometheus_utils.cc, opencensus/stats/internal/stats_manager_test.cc, opencensus/stats/internal/view_data_impl.cc
Pursuant to https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Export.md#aggregation-to-metric.
=> Change data type for Sum/int64 to int64.

opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
Found with: --config=asan -c opt
=> Fix memory leaks in GetIpAddress() and CurlEnv.

examples/grpc/BUILD, opencensus/exporters/stats/prometheus/BUILD
This was done in https://github.com/jupp0r/prometheus-cpp/pull/123
Fix our build.
=> Prometheus client library was split into "core" and "pull."

WORKSPACE, opencensus/common/internal/BUILD, opencensus/stats/BUILD, opencensus/trace/BUILD
Must be defined before grpc_deps().
=> com_google_benchmark should be com_github_google_benchmark.

opencensus/trace/internal/trace_config_impl.cc
Per https://github.com/census-instrumentation/opencensus-specs/pull/139
=> Reduce default limit on links to 32.

opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
=> Cleanup: break up "responses" into status vs context.

opencensus/common/BUILD, opencensus/common/version.h, opencensus/exporters/trace/stackdriver/BUILD, opencensus/exporters/trace/stackdriver/internal/stackdriver_exporter.cc
Fixes https://github.com/census-instrumentation/opencensus-cpp/issues/93
=> Add version to the Stackdriver agent label.

opencensus/context/internal/with_context.cc, opencensus/context/internal/with_context_test.cc, opencensus/context/with_context.h
While here, add an example in the comments.
=> Make WithContext conditional.

opencensus/context/README.md, opencensus/stats/README.md, opencensus/tags/README.md, opencensus/trace/README.md, opencensus/trace/span.h
* Add README for context/ dir.
* Add links to new materials on https://opencensus.io/.
* Improve span.h comments about thread safety and immutability.
=> Documentation updates.

RELEASING.md
- Add brief summary.
- Add example PRs.
- Add instructions on pinning build deps (fixes #130).
- Add CMake instructions.
- Use the releases page to create the tag based on a verified commit.
=> Update release instructions.

WORKSPACE
This reverts commit 002dea87ff7bdee39f08a2b19d69630147525575.
=> Unpin grpc, build works on Darwin again.

README.md
=> Correct product name and version number for supported version of Visual Studio 2017

examples/grpc/hello_client.cc, examples/grpc/hello_server.cc
This fixes the build.
See also: https://github.com/grpc/grpc/pull/18223
=> gRPC calls moved to grpc_impl namespace.

examples/grpc/hello_client.cc, examples/grpc/hello_server.cc
This reverts commit f26931034c380502ff06704c30dc9824e4abdcc0.
=> Revert "gRPC calls moved to grpc_impl namespace. (#297)"

opencensus/exporters/stats/stackdriver/README.md, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
=> Make Stackdriver stats exporter work with LastValue aggregation

cmake/OpenCensusDeps.cmake
Also display status as deps are being processed.
=> CMake: don't pull in benchmark dep if BUILD_TESTING=OFF.

opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.h, opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc, opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
=> StackdriverOptions: add monitored_resource.

examples/grpc/stackdriver.cc, opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc, opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
=> Stackdriver Stats exporter: allow override of metric_service_stub.

CMakeLists.txt
This should have been done in #356.
=> Bump CMake version to 0.5.0 also.

tools/pin_deps.py
=> Add com_google_googleapis to pin_deps.

CMakeLists.txt, cmake/OpenCensusDeps.cmake, cmake/OpenCensusHelpers.cmake, examples/helloworld/CMakeLists.txt, opencensus/common/internal/CMakeLists.txt, opencensus/context/CMakeLists.txt, opencensus/exporters/stats/prometheus/CMakeLists.txt, opencensus/exporters/stats/stdout/CMakeLists.txt, opencensus/exporters/trace/stdout/CMakeLists.txt, opencensus/stats/CMakeLists.txt, opencensus/tags/CMakeLists.txt, opencensus/trace/CMakeLists.txt, tools/travis/build_bazel.sh
The new version changes the amount of indentation.
=> Format with cmake-format 0.6.0.

WORKSPACE
https://github.com/jupp0r/prometheus-cpp/pull/311
=> Build fix: prometheus bazel files changed.

examples/grpc/hello_client.cc
Add a custom view with custom breakdown.
=> gRPC example: export stats from client as well as server.

opencensus/trace/CMakeLists.txt, opencensus/trace/exporter/span_exporter.h, opencensus/trace/internal/span_exporter.cc, opencensus/trace/internal/span_exporter_impl.cc, opencensus/trace/internal/span_exporter_impl.h, opencensus/trace/internal/span_exporter_test.cc
=> Make trace export interval and batch size configurable at runtime.

opencensus/stats/internal/stats_exporter.cc, opencensus/stats/internal/stats_exporter_impl.h, opencensus/stats/internal/stats_exporter_test.cc, opencensus/stats/stats_exporter.h
=> Make stats export interval configurable at runtime.

opencensus/stats/internal/stats_exporter_test.cc
Otherwise TSAN thinks we're relying on sleep().
=> stats_exporter_test: add lock around exported data.

opencensus/common/internal/CMakeLists.txt, opencensus/exporters/stats/prometheus/internal/prometheus_exporter.cc, opencensus/exporters/stats/prometheus/prometheus_exporter.h, opencensus/stats/CMakeLists.txt, opencensus/trace/CMakeLists.txt
https://github.com/jupp0r/prometheus-cpp/pull/323
=> Build fix: PrometheusExporter::Collect was made const.

WORKSPACE
=> Build fix: upb has namespaced bazel_version.

cmake/OpenCensusDeps.cmake, opencensus/common/internal/random.h, opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc, opencensus/stats/internal/delta_producer.h, opencensus/stats/internal/measure_registry_impl.h, opencensus/stats/internal/stats_exporter.cc, opencensus/stats/internal/stats_exporter_impl.h, opencensus/stats/internal/stats_exporter_test.cc, opencensus/stats/internal/stats_manager.h, opencensus/tags/internal/tag_key.cc, opencensus/trace/internal/local_span_store_impl.h, opencensus/trace/internal/running_span_store_impl.h, opencensus/trace/internal/span_exporter_impl.h, opencensus/trace/internal/span_exporter_test.cc, opencensus/trace/internal/span_impl.h
This is a change Abseil is making on their end.
=> Add an ABSL_ prefix to thread_annotation.h macros.

.travis.yml, opencensus/trace/internal/grpc_trace_bin_fuzzer.cc, tools/format.sh, tools/travis/check_format.sh
Trusty is EOL. Xenial is default since 2019-08-13.
=> Travis: upgrade the OS image from trusty to xenial.

opencensus/stats/internal/view_data_impl.cc, opencensus/stats/internal/view_data_impl.h, opencensus/stats/internal/view_data_impl_test.cc, opencensus/stats/internal/view_descriptor.cc, opencensus/stats/view_descriptor.h
fixes https://github.com/census-instrumentation/opencensus-cpp/issues/451
=> Add view data expiry

WORKSPACE
* Rename googletest branch.
* gRPC / proto needs @rules_python.
=> Build fix.

.github/workflows/build-and-test.yml
We used to do this on Travis, but haven't had working CI for a while.
=> Build and test using Github Actions.

.github/workflows/build-and-test.yml
cc @yashykt
In addition to running on push, run on PR creation
=> CI on pull request
