- opencensus/stats/internal/stats_exporter.cc
- opencensus/stats/stats_exporter.h
- opencensus/trace/BUILD
- opencensus/trace/exporter/span_exporter.h
- opencensus/trace/internal/message_event.cc
- opencensus/trace/internal/sampler_test.cc
- opencensus/trace/internal/span.cc
- opencensus/trace/internal/span_exporter.cc
- opencensus/trace/internal/span_exporter_impl.cc
- opencensus/trace/internal/span_exporter_impl.h
- opencensus/trace/internal/span_exporter_test.cc
- opencensus/trace/internal/span_options_test.cc
- opencensus/trace/internal/span_test.cc
- opencensus/trace/internal/trace_config.cc
- opencensus/trace/internal/trace_config_test.cc
- opencensus/trace/span.h
Also:
- Add sampler_test.
- Replace Span's default constructor with BlankSpan().
- Add BlankSpan test.
- Initialize threads after the rest of the exporter, to avoid racing.
> Make trace/ Exporter API consistent with the stats/ one.

- opencensus/stats/internal/measure_registry_impl.h
Fixing includes which was causing build errors on some systems.  Transitive includes function differently on some versions of gcc.  It was failing to build on gcc 6.3.0
> Include fix.

- opencensus/stats/BUILD
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/testing/test_utils.cc
- opencensus/stats/testing/test_utils.h
- opencensus/stats/view_data.h
This is needed for testing exporters without using the full View/Record
workflow.
> Add a test-only library granting access to the ViewData constructor.

- opencensus/BUILD
- opencensus/common/internal/BUILD
- opencensus/copts.bzl
- opencensus/stats/BUILD
- opencensus/stats/examples/BUILD
- opencensus/stats/measure_descriptor.h
- opencensus/trace/BUILD
- opencensus/trace/examples/BUILD
- opencensus/trace/internal/sampler.cc
- opencensus/trace/sampler.h
In particular, -Wno-sign-compare as Google style does not use unsigned
integers.
> Use the same copts as ABSL.

- opencensus/stats/BUILD
- opencensus/stats/internal/stats_manager_benchmark.cc
window combinations and varying numbers of views.
> Add a benchmark for stats, presently covering aggregation/aggregation

- opencensus/stats/internal/stats_exporter.cc
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/trace/internal/span_exporter_impl.cc
- opencensus/trace/internal/span_exporter_impl.h
Delay creation of exporter threads until a handler is registered, and do not include the time taken by the export in the export interval.
> Fix export intervals.

- opencensus/trace/internal/span_exporter_impl.cc
- opencensus/trace/internal/span_exporter_impl.h
Condition is run under span_mu_ so just read out the vector's size.
> Get rid of size_ and std::atomic.

- .travis.yml
- opencensus/plugins/BUILD
- opencensus/stats/examples/BUILD
A more aggressive fix for #29.
stats_plugin_end2end_test is minorly flaky locally but times out with very high probability in Travis, seemingly due to local-port issues--I hope to fix it eventually but blacklisting it seems the best solution for now.
exporter_example runs very slowly due to sleeps and does not provide value as a test.
> Add a "noci" tag for tests that should run locally and build but not run in Travis.

- .travis.yml
- ci.sh
Many Travis builds that require compiling protos are taking a very long time; this will hopefully help somewhat.
> Make Travis only build/run affected targets.

- ci.sh
- opencensus/exporters/stats/e2e/BUILD
- opencensus/exporters/stats/e2e/stackdriver_e2e_test.cc
- opencensus/exporters/stats/internal/stackdriver_utils.cc
- opencensus/exporters/stats/internal/stackdriver_utils.h
This writes to production Stackdriver and then uses Stackdriver's data retrieval API to check for successful export. It must be configured to communicate with a monitoring-enabled GCP project and is subject to network/Stackdriver outages, so it is marked manual.
> Add an end-to-end test for the Stackdriver stats exporter.

- opencensus/exporters/stats/e2e/stackdriver_e2e_test.cc
- opencensus/exporters/stats/internal/stackdriver_utils_test.cc
- opencensus/plugins/internal/stats_plugin_end2end_test.cc
- opencensus/stats/BUILD
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/examples/view_and_recording_example.cc
- opencensus/stats/internal/aggregation_window.h
- opencensus/stats/internal/debug_string_test.cc
- opencensus/stats/internal/set_aggregation_window.cc
- opencensus/stats/internal/set_aggregation_window.h
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/stats/internal/stats_manager_benchmark.cc
- opencensus/stats/internal/stats_manager_test.cc
- opencensus/stats/internal/view_data_impl.h
- opencensus/stats/internal/view_data_impl_test.cc
- opencensus/stats/internal/view_data_test.cc
- opencensus/stats/internal/view_descriptor.cc
- opencensus/stats/stats.h
- opencensus/stats/view_data.h
- opencensus/stats/view_descriptor.h
Most exporters can only handle Cumulative aggregation, and few users have need of Internal; this makes Cumulative the default and moves the ability to set Interval aggregation to a separate header in stats/internal. Pursuant to https://github.com/census-instrumentation/opencensus-specs/issues/47.
> Remove AggregationWindow from the public API.

- opencensus/stats/bucket_boundaries.h
- opencensus/stats/internal/bucket_boundaries.cc
This better accords with conventions (https://github.com/census-instrumentation/opencensus-cpp/blob/master/opencensus/doc/conventions.md#classes-that-take-an-object-and-store-it) and avoids a copy for the Linear and Exponential constructors.
Closes #21
> Change BucketBoundaries' internal constructor to take a vector by value.

- WORKSPACE
Using *.tar.gz instead of *.zip works around:
https://github.com/bazelbuild/bazel/issues/2656
> Depend on gRPC master branch.

- opencensus/stats/BUILD
- opencensus/stats/internal/recording.cc
- opencensus/stats/internal/stats_manager.cc
- opencensus/stats/internal/stats_manager.h
absl::Now() is remarkably expensive, and calling it for each ViewData was responsible for 6-8% of time spent in batched recording--after these changes total time in absl::Now() is negligible. (Log recording would move this off the critical path, but this would still help during log harvesting.)
> Record the present time once in Record() and pass that value to ViewInformation::Record().

- opencensus/trace/exporter/attribute_value.h
- opencensus/trace/internal/attribute_value.cc
This can potentially avoid materializing the AttributeValueRef object,
which is essentially POD and has no destructor.
> Pass AttributeValueRef by value to AttributeValue constructor.

- opencensus/trace/BUILD
- opencensus/trace/attribute_value_ref.h
- opencensus/trace/internal/attribute_value_ref_benchmark.cc
- opencensus/trace/internal/span_test.cc
This causes an accidental copy of the string, and (with VS2017) frees
that string before it's used:
https://github.com/census-instrumentation/opencensus-cpp/issues/22
> Don't pass std::string by value to AttributeValueRef()

- tools/ci.sh
Two issues:
- Modifications to BUILD files were not rerunning targets under that BUILD file due to counter-intuitive behavior in bazel query.
- The script's return value only depended on the final test, so errors in binary rules or library rules not depended on by any test were suppressed.
> Fix tools/ci.sh

- opencensus/trace/BUILD
- opencensus/trace/internal/span_test.cc
- opencensus/trace/span.h
Fixes https://github.com/census-instrumentation/opencensus-cpp/issues/43
> Change initializer_list to absl::Span to accept vectors and arrays.

- tools/ci.sh
e.g. When the affected tests are all tagged "noci"
> ci.sh: return success when no tests are affected even though builds are.

- opencensus/plugins/grpc/BUILD
- opencensus/plugins/grpc/internal/grpc_plugin_benchmark.cc
This is likely not a very good benchmark (in particular, it somewhat unrealistically introduces client/server contention when recording stats) but provides a starting point for profiling.
> Add a simple gRPC benchmark.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stdout/internal/stdout_exporter.cc
- opencensus/stats/BUILD
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/internal/stats_exporter.cc
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/stats/stats_exporter.h
Add an interface for pull exporters, and disallow registering non-cumulative views--Stackdriver and Prometheus both require cumulative views, and allowing but then ignoring cumulative views is likely confusing.
> Changes to the stats exporter interface

- tools/bazel.rc
- tools/presubmit.sh
The bazel.rc file has configs for address sanitizer (--config=asan) and
ubsan.
The presubmit script is a heavyweight version of tools/ci.sh which
builds and tests everything, including opt mode and sanitizers.
> Add bazel.rc and presubmit script.

- opencensus/exporters/stats/prometheus/internal/prometheus_test_server.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_e2e_test.cc
- opencensus/stats/BUILD
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/internal/stats_exporter.cc
- opencensus/stats/internal/stats_exporter_impl.h
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/stats/internal/view_descriptor.cc
- opencensus/stats/stats_exporter.h
- opencensus/stats/view_descriptor.h
An API change for consideration: right now, registering a view for export uses a function in StatsExporter, and registering a view for on-task consumption uses the constructor of View. By moving those registration functions to ViewDescriptor, I think it becomes easier to find how to use it by following headers. (It also allows removing StatsExporter from the main user API--it will only be needed for unregistering views and writing exporters.)
WIP: needs implementation, removal/deprecation of competing functions.
> Add registration interfaces to ViewDescriptor.

- opencensus/plugins/grpc/BUILD
- opencensus/plugins/grpc/grpc_plugin.h
- opencensus/plugins/grpc/internal/stats_plugin_end2end_test.cc
- opencensus/plugins/grpc/internal/views.cc
- opencensus/stats/BUILD
Uses RegisterForExport() from #61.
> Define canonical gRPC views.

- opencensus/plugins/grpc/BUILD
- opencensus/plugins/grpc/internal/stats_plugin_end2end_test.cc
Two changes:
- Switch to IPv4--for some reason this fixes the consistent timeouts, despite our Travis configuration nominally supporting IPv6 loopback.
- Add some short sleeps to give the server a chance to update stats before verifying.
> Reenable the stats_plugin_end2end_test on ci.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stdout/internal/stdout_exporter.cc
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/internal/stats_exporter.cc
- opencensus/stats/internal/stats_exporter_impl.h
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/stats/stats_exporter.h
- opencensus/stats/view_data.h
This allows the Stackdriver exporter to batch TimeSeries from different views into the same RPCs.
stackdriver_e2e_test run manually.
> Change the stats exporter interface to batch all views together.

- WORKSPACE
- examples/grpc/BUILD
- opencensus/exporters/stats/prometheus/BUILD
Changed upstream in https://github.com/jupp0r/prometheus-cpp/pull/97.
> Update the prometheus_cpp workspace name.

- opencensus/trace/internal/span.cc
Followup to: https://github.com/census-instrumentation/opencensus-cpp/pull/70
> In debug builds, assert() that End() isn't called more than once.

- opencensus/stats/BUILD
- opencensus/stats/internal/tag_set.cc
- opencensus/stats/internal/tag_set_test.cc
- opencensus/stats/stats.h
- opencensus/stats/tag_set.h
This is needed for the DeltaProducer--the ViewData maps include only the tag values in ViewDescriptor order, but since the DeltaProducer aggregates before view aggregation we need to keep the entire mapping.
> Add a TagSet class providing equality and hashing for key/value maps.

- opencensus/trace/internal/span.cc
- opencensus/trace/internal/span_impl.cc
- opencensus/trace/internal/span_impl.h
Inline EndWithTime() into its one caller.
> Close a race by checking for repeated End() calls in SpanImpl.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_e2e_test.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
Stackdriver has fixed the backend limitations that constrained this previously. I ran the expanded e2e test locally.
> Increase Stackdriver CreateTimeSeries batch size.

- opencensus/stats/BUILD
- opencensus/stats/internal/delta_producer.cc
- opencensus/stats/internal/delta_producer_stats_test.cc
- opencensus/stats/internal/measure_data.cc
- opencensus/stats/internal/measure_data.h
- opencensus/stats/internal/stats_manager.cc
- opencensus/stats/internal/stats_manager.h
- opencensus/stats/internal/view_data_impl.cc
- opencensus/stats/internal/view_data_impl.h
> Add DeltaProducer harvesting.

- examples/helloworld/helloworld.cc
- opencensus/exporters/stats/prometheus/internal/prometheus_test_server.cc
- opencensus/exporters/stats/prometheus/internal/prometheus_utils_test.cc
- opencensus/exporters/stats/stackdriver/README.md
- opencensus/exporters/stats/stackdriver/internal/stackdriver_e2e_test.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
- opencensus/plugins/grpc/internal/measures.cc
- opencensus/plugins/grpc/internal/measures.h
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/examples/view_and_recording_example.cc
- opencensus/stats/internal/debug_string_test.cc
- opencensus/stats/internal/delta_producer_stats_test.cc
- opencensus/stats/internal/measure.cc
- opencensus/stats/internal/measure_registry.cc
- opencensus/stats/internal/measure_registry_impl.cc
- opencensus/stats/internal/measure_registry_impl.h
- opencensus/stats/internal/measure_registry_test.cc
- opencensus/stats/internal/stats_exporter_test.cc
- opencensus/stats/internal/stats_manager.cc
- opencensus/stats/internal/stats_manager.h
- opencensus/stats/internal/stats_manager_benchmark.cc
- opencensus/stats/internal/stats_manager_test.cc
- opencensus/stats/measure.h
- opencensus/stats/measure_descriptor.h
- opencensus/stats/measure_registry.h
- opencensus/stats/recording.h
This completes moving away from direct interaction with the registries in the core stats workflows (after moving RegisterForExport from the StatsExporter to the ViewDescriptor). 
After this, the only use keeping MeasureRegistry in the public API is the possibility of measures shared between libraries with no common initialization (e.g. an rpc_latency measure shared between RPC libraries), for which we presently encourage looking up the measure and registering it if not found. I think we should consider recommending that such libraries either use individual measures or depend on a common measure definition package and make MeasureRegistry internal.
> Move measure registration to Measure from MeasureRegistry.

- opencensus/common/internal/grpc/BUILD
- opencensus/common/internal/grpc/status.cc
- opencensus/common/internal/grpc/status.h
- opencensus/common/internal/grpc/status_test.cc
- opencensus/exporters/stats/stackdriver/BUILD
- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/trace/stackdriver/internal/stackdriver_exporter.cc
Also convert StatusCode from a number to a name.
> Factor out ToString(grpc::Status).

- opencensus/exporters/trace/stdout/internal/stdout_exporter.cc
- opencensus/exporters/trace/stdout/internal/stdout_exporter_test.cc
- opencensus/exporters/trace/stdout/stdout_exporter.h
- opencensus/trace/exporter/span_exporter.h
- opencensus/trace/internal/span_exporter.cc
- opencensus/trace/internal/span_exporter_impl.cc
- opencensus/trace/internal/span_exporter_impl.h
- Make StdoutExporter take an ostream.
- Make stdout_exporter_test faster (no sleep) and check that
the added annotation appears in the output.
> Bring back SpanExporter::ExportForTesting.

- opencensus/stats/internal/measure_data.cc
- opencensus/stats/internal/measure_data.h
- opencensus/stats/internal/view_data_impl.cc
- opencensus/stats/internal/view_data_impl.h
- opencensus/stats/internal/view_data_impl_test.cc
- opencensus/stats/testing/test_utils.cc
And fix a bug revealed in AddToDistribution with StatsObjects.
> Remove MeasureData::Add(), only used in tests.

- WORKSPACE
Prometheus converted its APIs from the deprecated protobufs (https://github.com/jupp0r/prometheus-cpp/pull/105 )--this pins to before the commit until we update the Prometheus exporter.
> Temporarily pin the Prometheus repository to fix our build.

- WORKSPACE
absl no longer needs it as of https://github.com/abseil/abseil-cpp/commit/af7882601aad93ada881486eeaabc562f1733961
> Remove dependency on cctz.

- opencensus/exporters/stats/prometheus/internal/prometheus_utils.cc
- opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
> Mark some unused things as unused to quiet warnings.

- opencensus/stats/measure.h
- opencensus/stats/tag_key.h
Inspired by concern about whether the style guide allowed our recommended function-wrapping-a-static style: https://github.com/grpc/grpc/pull/15196.
> Document that Measure/TagKey have trivial destructors.

- examples/grpc/hello_server.cc
GetSpanFromServerContext() comes from <grpcpp/opencensus.h> as of
https://github.com/grpc/grpc/pull/15984
> Don't depend on gRPC private header.

- examples/grpc/BUILD
- examples/grpc/hello_client.cc
- opencensus/exporters/stats/stackdriver/README.md
- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
This makes it look more like trace::StackdriverExporter, and reduces
includes.
> Simplify stats::StackdriverExporter.

- opencensus/stats/BUILD
- opencensus/stats/tag_key.h
- opencensus/stats/tag_set.h
- opencensus/tags/BUILD
- opencensus/tags/internal/tag_key.cc
- opencensus/tags/internal/tag_key_test.cc
- opencensus/tags/internal/tag_map.cc
- opencensus/tags/internal/tag_map_test.cc
- opencensus/tags/tag_key.h
- opencensus/tags/tag_map.h
- Move stats::TagKey and stats::TagSet (renamed to TagMap) to tags::
- Add compatibility shims with deprecation warning.
This commit does not break the API.
> Introduce the opencensus::tags namespace.

- opencensus/trace/internal/span_context.cc
- opencensus/trace/internal/span_context_test.cc
- opencensus/trace/span_context.h
Motivated by EXPECT_NE() in unit tests.
> Add operator!= to SpanContext.

- tools/appveyor/build.bat
- tools/appveyor/install.bat
- tools/appveyor/test.bat
It's no longer required, new versions of bazel fix the problem of long paths.
> Windows: remove --output_user_root workaround.

- opencensus/trace/internal/span.cc
- opencensus/trace/span.h
Also, improve documentation and be explicit about copies and moves.
> Mark all Span methods const.

- opencensus/context/BUILD
- opencensus/context/context.h
- opencensus/context/internal/context.cc
- opencensus/context/internal/context_test.cc
- opencensus/context/internal/with_context.cc
- opencensus/context/internal/with_context_test.cc
- opencensus/context/with_context.h
- opencensus/trace/internal/span.cc
- opencensus/trace/span.h
Context holds information specific to an operation, such as a TagMap and
Span. Each thread has a currently active Context. Contexts are conceptually
immutable: the contents of a Context cannot be modified in-place.
> Draft implementation of Context.

- opencensus/context/internal/with_context.cc
- opencensus/context/internal/with_context_test.cc
- opencensus/context/with_context.h
This only happens in debug mode (!NDEBUG).
Add a death test for it.
> Check that WithContext is constructed and destructed on the same thread.

- .travis.yml
We don't run format.sh on Darwin in the first place.
> Travis: skip installing buildifier on Darwin.

- opencensus/tags/internal/tag_map.cc
Put an ifdef around it to avoid a warning.
> compare_keys is unused when NDEBUG is defined.

- opencensus/context/BUILD
- opencensus/context/internal/context_test.cc
Especially when Wrap()ing functions.
This is easier now that we have the With* classes and utilities.
> Make context_test expect the right tags and span.

- opencensus/exporters/stats/prometheus/internal/prometheus_utils.cc
In https://github.com/jupp0r/prometheus-cpp/pull/169
> prometheus/metric.h was deleted as dead code.

- opencensus/stats/BUILD
Previously the build picked these up transitively. It's better
to be explicit.
> Add absl deps that stats headers use.

- opencensus/common/internal/BUILD
- opencensus/context/BUILD
- opencensus/exporters/stats/stdout/BUILD
- opencensus/exporters/trace/stackdriver/BUILD
- opencensus/stats/BUILD
- opencensus/trace/BUILD
- Add dependencies we were previously picking up transitively.
- Remove unnecessary dependencies.
> Cleanups for BUILD files.

- .travis.yml
- tools/appveyor/install.bat
bazel 0.17.1 ignores HOME/.bazelrc (where we configure caching) if WORKSPACE/.bazelrc is present (which I populated in https://github.com/census-instrumentation/opencensus-cpp/commit/877550f3d72ef31aad662b1baf9d070fc22ce1b9 and broke caching).
Upgrade to bazel 0.19.2 which doesn't have this problem.
> Unbreak caching on Travis.

- opencensus/tags/internal/with_tag_map_benchmark.cc
This makes the benchmark crash in non-opt mode.
> Fix duplicate keys in with_tag_map_benchmark.cc.

- opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
Before:
`curl error: Couldn't connect to server`
After:
`ZipkinExporter: curl error: Couldn't connect to server (sending to "http://127.0.0.1:9412/api/v2/spans")`
> Make ZipkinExporter errors clearer.

- .travis.yml
- WORKSPACE
- tools/appveyor/install.bat
- tools/zlib/BUILD
- tools/zlib/README.md
- tools/zlib/WORKSPACE
* Upgrade bazel to 0.20.0 where the old rule is gone.
* `repo_mapping` is gone, join the diamond using a `local_repository`
in `tools/zlib/`.
* appveyor: remove the Windows temporary directory we stopped using
in #198.
> Build fix: switch to new http_archive rule.

- .travis.yml
- tools/travis/build_bazel.sh
- tools/travis/build_cmake.sh
- tools/travis/check_format.sh
* Move scripts from .travis.yaml to tools/travis/*.sh.
* Run format.sh first, and separately from build tests.
* Run cmake_format on Travis.
* Build and test with bazel + gcc (previously only clang).
* Build and test with CMake.
> Travis: add gcc and CMake.

- opencensus/trace/BUILD
Previously it was picking it up transitively.
> :context_util_test depends on :span_context.

- WORKSPACE
- cmake/abseil.CMakeLists.txt
- cmake/googletest.CMakeLists.txt
- cmake/prometheus-cpp.CMakeLists.txt
> Pin versions of dependencies in preparation for release.

- opencensus/trace/internal/span_exporter_impl.cc
- opencensus/trace/internal/span_exporter_impl.h
Otherwise sampled spans will pile up in memory.
> Don't collect spans for export until an exporter has been registered.

- opencensus/common/internal/CMakeLists.txt
- opencensus/stats/CMakeLists.txt
This adds NOMINMAX as a public/interface definition to the targets `opencensus_common_stats_object` and `opencensus_stats_core`
> Add NOMINMAX definitions when compiling with MSVC

- .appveyor.yml
This is WIP, ref #289 
I'm not familiar at all with bazel builds, so I'm starting with CMake. That's also an incentive to expand the CMake support ;)
It looks like appveyor has support for `vcpkg` as well, so it could be used to test a future vcpkg-build of opencensus with find_package for dependencies :)
That said, supporting both is an option: https://github.com/google/googletest/blob/master/appveyor.yml
> Fix Windows builds with appveyor

- tools/format.sh
This file comes from upstream, so let's keep it as-is.
This file will be added in #290.
> Don't autoformat FetchContent.cmake.

- opencensus/trace/span.h
There's already a warning about thread safety in the comments.
Without this change, Context can't be move-assigned.
Fixes #295.
> Allow Span move-assignment.

- opencensus/copts.bzl
absl copts build flags has been updated to ABSL_* 
this fixes build error
> Fix absl cops flag names.

- .bazelrc
bazel 0.24.1 doesn't support it, and we haven't used it since
commit 11f65c83459b4d2aafe47feed16bf458a5c3b088.
> Remove --experimental_enable_repo_mapping.

- tools/format.sh
This adds parameters for skipping the sed operations and/or the operations that require installed software (clang-format, cmake-format ...).
The usage scenario is that @g-easy 's Docker-container is not useable in Windows Docker because the sed operations fail. However, the workaround is easy:
- Install Git for Windows - this gives you a bash shell. Run format.sh from here, skipping the operations requiring installed software
- Use @g-easy 's Docker container for the operations requiring installed software.
I have tested this, and it works very well :)
> Added parameters to tools/format.sh (Windows)

- tools/docker-format/Dockerfile
- tools/travis/check_format.sh
Version 0.5.1 changes the formatting (which breaks "check format" on
travis) but also breaks add_library(ALIAS) so we can't upgrade.
Upstream issue: https://github.com/cheshirekow/cmake_format/issues/111
> Pin cmake_format to version 0.4.5.

- examples/grpc/BUILD
Add separate targets for:
* proto_library
* cc_proto_library
* cc_grpc_library
> Use proto best practices.

- cmake/OpenCensusDeps.cmake
- cmake/OpenCensusHelpers.cmake
- opencensus/stats/CMakeLists.txt
- opencensus/trace/CMakeLists.txt
- tools/docker-format/Dockerfile
- tools/format.sh
- tools/travis/check_format.sh
> Unpin cmake_format after v0.5.2 bug fixes.

- WORKSPACE
- opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
This is cleaner than having it in the build rule.
> Move RAPIDJSON_HAS_STDSTRING define to Zipkin exporter code.

- tools/zlib/BUILD
grpc renamed @com_github_madler_zlib//:z to @zlib//:zlib in
https://github.com/grpc/grpc/commit/79f7abb45eab9f6f49ba694d4f8ce70f8e142b1d#diff-5952172e3b803ed640371cda4cddf13d
> zlib build fix.

- opencensus/trace/internal/span.cc
- opencensus/trace/internal/span_impl.cc
- opencensus/trace/internal/span_impl.h
- opencensus/trace/internal/span_test.cc
- opencensus/trace/span.h
- tools/travis/build_bazel.sh
Allows changing the span name after the constructor before the span end.
This is needed for envoyproxy/envoy which updates the span name during the request route configuration.
Currently, it uses an annotation which leads to strange span values:
```
Name: ingress (From Client)
TraceId-SpanId-Options: 09d76941cce57c762c600ad861e120e3-57f2c613dc9714a0-01
Parent SpanId: 91b716c92ee92e57 (remote: true)
Start time: 2019-06-24T13:47:07.150968383-07:00
End time: 2019-06-24T13:47:07.153027742-07:00
Attributes: (0 dropped)
Annotations: (0 dropped)
2019-06-24T13:47:07.151008446-07:00: setOperation (attributes: "operation":"ServerRoute")
2019-06-24T13:47:07.151011373-07:00: setOperation (attributes: "operation":"ClientRoute")
Message events: (0 dropped)
Links: (0 dropped)
Span ended: true
Status: OK …
```
> Add Span::SetName()

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.h
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
Follow up of #334. In addition to general custom monitored resource, also add per view custom monitored resource. This could be useful in the case of using envoy exporting istio metric, where inbound metrics attached to k8s_container MR and outbound metrics attached to k8s_pod (https://cloud.google.com/monitoring/api/metrics_anthos).
> Add per view monitored resource into stackdriver exporter option

- opencensus/exporters/trace/zipkin/BUILD
- opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
- Depend on absl/time directly instead of transitively.
- Simplify string::compare calls.
> Zipkin exporter nits.

- examples/grpc/stackdriver.cc
- opencensus/common/internal/BUILD
- opencensus/common/internal/CMakeLists.txt
- opencensus/common/internal/hostname.cc
- opencensus/common/internal/hostname.h
- opencensus/common/internal/hostname_test.cc
- opencensus/exporters/stats/stackdriver/BUILD
- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
Have the exporter fill it in by default, and move the code out of
examples/ and into opencensus/common/internal/.
> Stackdriver stats exporter: make opencensus_task optional.

- WORKSPACE
gRPC depends on upb which depends on bazel_version, which
has to be instantiated in WORKSPACE.
The bazel_version definition is here:
https://github.com/protocolbuffers/upb/blob/1ee1e362565f681fdd46f16bf9f70f51c905ddd4/bazel/repository_defs.bzl
> Build fix: provide a @bazel_version repository.

- opencensus/trace/internal/b3.cc
> Make B3 parser more readable.

- WORKSPACE
- tools/pin_deps.py
Need rules_cc for abseil and build_bazel_rules_apple for grpc.
> Build fix.

- opencensus/stats/internal/view_data_impl.cc
View data switch without default causes compiler warnings.
Addition of a default removes these warnings.
> Add default cases for view data switch

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.h
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
* Don't send a CreateMetricDescriptor RPC.
* Don't add the opencensus_task label.
Fixes #372.
> Stackdriver stats: improve handling of builtin metrics.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
- opencensus/exporters/trace/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/trace/stackdriver/stackdriver_exporter.h
Also improve logging when exporter RPCs fail.
> Make default Stackdriver exporter deadlines match opencensus-java.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.h
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
- Don't add the opencensus_task label when a non-default
MonitoredResource is present.
- Refactor exporter code to reduce duplication of effort.
> Stackdriver stats: resource must uniquely identify a timeseries.

- opencensus/exporters/trace/ocagent/internal/ocagent_exporter.cc
- opencensus/trace/internal/span_id.cc
- opencensus/trace/internal/trace_id.cc
- opencensus/trace/span_id.h
- opencensus/trace/trace_id.h
* Trace/Span IDs need to be binary, not hex encoded.
* Don't set parent_span_id on root spans.
Found by: @inigohu
> Fix ocagent trace exporter.

- opencensus/stats/internal/measure_registry_impl.cc
- opencensus/stats/internal/measure_registry_impl.h
- opencensus/stats/internal/measure_registry_test.cc
Heap-allocate MeasureDescriptors so that references to them are stable
even if the underlying storage (std::vector) in the MeasureRegistry
moves.
Add test that fails under ASAN if this isn't done.
> Fix invalidation of MeasureDescriptors.

- opencensus/tags/internal/tag_key.cc
- opencensus/tags/internal/tag_key_test.cc
Allocate name strings separately so that references to them are stable
even if the underlying storage grows / moves.
Add test that fails if this isn't done.
> Fix invalidation of TagKeys.

- opencensus/common/internal/timestamp_benchmark.cc
Move the proto constructor out of the loop.
> Speed up SetTimestamp benchmark.

- examples/helloworld/BUILD
- opencensus/common/internal/BUILD
- opencensus/context/BUILD
- opencensus/exporters/trace/ocagent/BUILD
- opencensus/exporters/trace/zipkin/BUILD
- opencensus/stats/BUILD
- opencensus/tags/BUILD
- Explicitly passing -pthread isn't needed anymore.
- Don't rely on transitive deps.
- Several targets didn't need core_headers.
> Tidy up BUILD files.

- opencensus/context/context.h
- opencensus/context/internal/context.cc
- opencensus/context/internal/context_test.cc
Add a test that otherwise finds this leak under ASAN.
Fixes #416
> Free per-thread Context memory on thread exit.

- opencensus/exporters/trace/zipkin/internal/zipkin_exporter.cc
- opencensus/exporters/trace/zipkin/internal/zipkin_exporter_test.cc
- opencensus/exporters/trace/zipkin/zipkin_exporter.h
Always branch on af_type == v4, instead of mixing v4 and v6.
> Don't leave af_type uninitialized.

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
- opencensus/exporters/stats/stackdriver/stackdriver_exporter.h
Move and rename the stackdriver exporter Handler to the header. Add a method which allows a subclass to apply a custom logic to modify the GrpcClientContext. I.e. to add CallCredentials
> Move and rename the stackdriver exporter Handler to header, add virtual PrepareClientContext

- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc
- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils_test.cc
- opencensus/exporters/stats/stdout/internal/stdout_exporter.cc
- opencensus/stats/examples/exporter_example.cc
- opencensus/stats/internal/view_data.cc
- opencensus/stats/internal/view_data_impl.cc
- opencensus/stats/internal/view_data_impl.h
- opencensus/stats/internal/view_data_impl_test.cc
- opencensus/stats/testing/test_utils.cc
- opencensus/stats/testing/test_utils.h
- opencensus/stats/view_data.h
This fixes a bug reporting metrics to stackdriver. Cumulative timeseries metrics in Stackdriver should report a start time which contains the first set of points updated for that timeseries.
Before this PR, the start_time was picked once for the view (regardless of which tagmap was exporting a timeseries). This causes issues in Stackdriver when a new timeseries(i.e. a new tagmap for the same view) is reported to Stackdriver at a later time. Stackdriver has internal mechanisms which can cause those initial points to be dropped.
> Update ViewData+StackdriverExporter to use a separate start_timestamp for each tag map.

- opencensus/copts.bzl
OpenCensus compares signed and unsigned values throughout the code. This appears to be a conscious decision, and one that many projects take.
It also relies on Abseil to provide a sane set of compile/warning flags. However, Abseil has recently (https://github.com/abseil/abseil-cpp/commit/5bf048b8425cc0a342e4647932de19e25ffd6ad7) stopped disabling warnings for signed/unsigned comparisons.
The base set of flags provided by Abseil no longer align with OpenCensus's approach. So, this PR adds an additional warning flag to disable these warnings directly.
> Disable signed/unsigned comparison warnings

- opencensus/trace/internal/span_exporter_impl.cc
Fixing this message from clang:
```
opencensus/trace/internal/span_exporter_impl.cc:68:24: warning: comparison of integers of different signs: 'std::vector::size_type' (aka 'unsigned long') and 'const int' [-Wsign-compare]
return spans_.size() >= cached_batch_size_;
~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
1 warning generated.
```
> Silence -Wsign-compare compiler warning.

- opencensus/common/internal/stats_object.h
<N> at the end of the constructor causes a build failure in GCC 11 compiled with -std=c++20
> [BUG FIX] Fix template syntax error

- opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc
This allows metric descriptors to be created for metrics in that domain
> Stackdriver exporter: add workload.googleapis.com as a supported external domain

- .github/workflows/build-and-test.yml
- .gitignore
- CMakeLists.txt
- cmake/OpenCensusConfig.cmake.in
- cmake/OpenCensusDeps.cmake
- cmake/OpenCensusHelpers.cmake
- opencensus/common/internal/CMakeLists.txt
- opencensus/stats/CMakeLists.txt
- opencensus/trace/CMakeLists.txt
1. support install and find_package
2. fix dependencies version
3. use external abseil and prometheus-cpp if possible
4. fix abseil build option
5. add flag to disable test
6. fix issue that target name is different if is included as sub directory
7. enable ci for cmake build
> cmake improvement

- opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc
We previously assumed that task labels are not needed if a non-default MonitoredResource is used, and that a MonitoredResource would be able to identify the timeseries, but this assumption breaks in the following cases -
1) Application is running under GCE, but there are two binaries running on the same VM. In this case, the MonitoredResource for both binaries would be the same. It would get `gce_instance` as the type and the labels `project_id`, `instance_id` and `zone` would be the same for both binaries.
2) If for some reason, the binary is unable to identify the GCP MonitoredResource and ends up using "global", we would still want to unique identify it from other binaries, and still be able to create unique time series for the two.
> Stats StackDriverExporter: Always add task label for known custom metrics
